// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnx2jQ9Jlxfpm1eYQJPXzBCEEXGHe8xw0',
    appId: '1:1015868760588:web:c202f46967195d4991c429',
    messagingSenderId: '1015868760588',
    projectId: 'learn-todo-app-404b7',
    authDomain: 'learn-todo-app-404b7.firebaseapp.com',
    storageBucket: 'learn-todo-app-404b7.appspot.com',
    measurementId: 'G-TCXE8S749Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPM_Mem_zxUxj-EHAP6DD6E-7uqRuEjsw',
    appId: '1:1015868760588:android:eedae24bf7d850a291c429',
    messagingSenderId: '1015868760588',
    projectId: 'learn-todo-app-404b7',
    storageBucket: 'learn-todo-app-404b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvh21zzGUkAAPi1twLJ9eKqbirvTIiKi0',
    appId: '1:1015868760588:ios:56ba38a8e638b86e91c429',
    messagingSenderId: '1015868760588',
    projectId: 'learn-todo-app-404b7',
    storageBucket: 'learn-todo-app-404b7.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvh21zzGUkAAPi1twLJ9eKqbirvTIiKi0',
    appId: '1:1015868760588:ios:56ba38a8e638b86e91c429',
    messagingSenderId: '1015868760588',
    projectId: 'learn-todo-app-404b7',
    storageBucket: 'learn-todo-app-404b7.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnx2jQ9Jlxfpm1eYQJPXzBCEEXGHe8xw0',
    appId: '1:1015868760588:web:ef78e336fd17280c91c429',
    messagingSenderId: '1015868760588',
    projectId: 'learn-todo-app-404b7',
    authDomain: 'learn-todo-app-404b7.firebaseapp.com',
    storageBucket: 'learn-todo-app-404b7.appspot.com',
    measurementId: 'G-MSRYHWSQMR',
  );
}
